package Constantes;

public class Ctes {
    public static final int LARGEUR_ECRAN = 800;
    public static final int HAUTEUR_ECRAN = 600;
    public static final int NOMAP_VALUE = -99999;
    
    public static final int ACCUEIL_X_BTNNEW = 199;
    public static final int ACCUEIL_Y_BTNNEW = 199;
    public static final int ACCUEIL_X_BTNCONTINUE = 199;
    public static final int ACCUEIL_Y_BTNCONTINUE = 299;
    public static final int ACCUEIL_X_BTNQUIT = 199;
    public static final int ACCUEIL_Y_BTNQUIT = 399;
    
    public static final int MENUBARRE_X_BARRE = 0;
    public static final int MENUBARRE_Y_BARRE = 550;
    public static final int MENUBARRE_X_VIE = MENUBARRE_X_BARRE + 479;
    public static final int MENUBARRE_Y_VIE = MENUBARRE_Y_BARRE + 21;
    public static final int MENUBARRE_X_MANA = MENUBARRE_X_BARRE + 641;
    public static final int MENUBARRE_Y_MANA = MENUBARRE_Y_BARRE + 21;
    public static final int MENUBARRE_X_CASEEQUIP = MENUBARRE_X_BARRE + 9;
    public static final int MENUBARRE_Y_CASES = MENUBARRE_Y_BARRE + 9;
    public static final int MENUBARRE_ESP_CASES = 42;
    public static final int MENUBARRE_X_CASEINV = MENUBARRE_X_BARRE + 189;
    public static final int MENUBARRE_X_SELECTSTUFF = MENUBARRE_X_BARRE + 7;
    public static final int MENUBARRE_X_SELECTINV = MENUBARRE_X_BARRE + 187;
    public static final int MENUBARRE_Y_SELECT = MENUBARRE_Y_BARRE + 7;
    public static final int MENUBARRE_TAILLE_CASE = 38;
    public static final int MENUBARRE_X_CARACS = MENUBARRE_X_BARRE + 757;
    public static final int MENUBARRE_Y_CARACS = MENUBARRE_Y_BARRE + 9;
    
    public static final int NEWGAME_X_BTNCHEVALIER = 149;
    public static final int NEWGAME_Y_BTNCHEVALIER = 199;
    public static final int NEWGAME_X_BTNASSASSIN = 449;
    public static final int NEWGAME_Y_BTNASSASSIN = 199;
    public static final int NEWGAME_X_BTNSORCIER = 149;
    public static final int NEWGAME_Y_BTNSORCIER = 299;
    public static final int NEWGAME_X_BTNPRETRE = 449;
    public static final int NEWGAME_Y_BTNPRETRE = 299;
    public static final int NEWGAME_X_BTNRETOUR = 199;
    public static final int NEWGAME_Y_BTNRETOUR = 449;
    
    public static final int CONTINUEGAME_X_SUIV = 617;
    public static final int CONTINUEGAME_Y_SUIV = 477;
    public static final int CONTINUEGAME_X_PREC = 53;
    public static final int CONTINUEGAME_Y_PREC = 477;
    public static final int CONTINUEGAME_X_RETOUR = 249;
    public static final int CONTINUEGAME_Y_RETOUR = 522;
    public static final int CONTINUEGAME_X_CADRESAVE = 75;
    public static final int CONTINUEGAME_Y_CADRESAVE = 127;
    public static final int CONTINUEGAME_ESP_CADRESAVE = 65;
    public static final int CONTINUEGAME_X_CLASS = CONTINUEGAME_X_CADRESAVE + 8;
    public static final int CONTINUEGAME_Y_TEXT = CONTINUEGAME_Y_CADRESAVE + 15;
    public static final int CONTINUEGAME_X_NIV = CONTINUEGAME_X_CADRESAVE + 105;
    public static final int CONTINUEGAME_X_FAME = CONTINUEGAME_X_CADRESAVE + 180;
    public static final int CONTINUEGAME_X_JOUER = 352;
    public static final int CONTINUEGAME_Y_JOUER = 454;
    public static final int CONTINUEGAME_X_SUPP = CONTINUEGAME_X_CADRESAVE + 520;
    public static final int CONTINUEGAME_X_CASE = CONTINUEGAME_X_CADRESAVE + 332;
    public static final int CONTINUEGAME_Y_CASE = CONTINUEGAME_Y_CADRESAVE + 8;
    public static final int CONTINUEGAME_ESP_CASE = 42;
    
    public static final int VILLAGE_X_IMGBANK = 60;
    public static final int VILLAGE_Y_IMGBANK = 100;
    public static final int VILLAGE_X_MENUBANK = 0;
    public static final int VILLAGE_Y_MENUBANK = 0;
    public static final int VILLAGE_X_TELEPFIGHT = 500;
    public static final int VILLAGE_Y_TELEPFIGHT = 500;
    public static final int VILLAGE_X_STARTPERSO = 320;
    public static final int VILLAGE_Y_STARTPERSO = 280;
    public static final int VILLAGE_X_FONTAINE = 365;
    public static final int VILLAGE_Y_FONTAINE = 240;
    
    public static final int BANK_X_FOND = 318;
    public static final int BANK_Y_FOND = 100;
    public static final int BANK_X_FERMER = BANK_X_FOND + 195;
    public static final int BANK_Y_FERMER = BANK_Y_FOND + 7;
    public static final int BANK_X_RETIRER = BANK_X_FOND + 7;
    public static final int BANK_Y_RETIRER = BANK_Y_FOND + 7;
    public static final int BANK_X_STOCKER = BANK_X_FOND + 97;
    public static final int BANK_Y_STOCKER = BANK_Y_FOND + 7;
    public static final int BANK_X_SELECT = BANK_X_FOND + 7;
    public static final int BANK_Y_SELECT = BANK_Y_FOND + 39;
    public static final int BANK_ESP_SELECT = 42;
    public static final int BANK_Y_SELECT_INV = BANK_Y_FOND + 304;
    public static final int BANK_CONTENANCE = 36;
    public static final int BANK_TAILLE_CASE = 38;
    
    public static final int ECHAP_X_FOND = 255;
    public static final int ECHAP_Y_FOND = 83;
    public static final int ECHAP_X_REPRENDRE = ECHAP_X_FOND + 58;
    public static final int ECHAP_Y_REPRENDRE = ECHAP_Y_FOND + 119;
    public static final int ECHAP_X_SAVE = ECHAP_X_FOND + 58;
    public static final int ECHAP_Y_SAVE = ECHAP_Y_FOND + 215;
    public static final int ECHAP_X_QUITTER = ECHAP_X_FOND + 58;
    public static final int ECHAP_Y_QUITTER = ECHAP_Y_FOND + 283;
    
    public static final int CARACS_X_FOND = 450;
    public static final int CARACS_Y_FOND = 217;
    public static final int CARACS_X_CLASS = CARACS_X_FOND + 16;
    public static final int CARACS_Y_CLASS = CARACS_Y_FOND + 13;
    public static final int CARACS_X_NIVEAU = CARACS_X_FOND + 16;
    public static final int CARACS_Y_NIVEAU = CARACS_Y_FOND + 52;
    public static final int CARACS_X_BARREXP = CARACS_X_FOND + 17;
    public static final int CARACS_Y_BARREXP = CARACS_Y_FOND + 72;
    public static final int CARACS_X_XP = CARACS_X_FOND + 16;
    public static final int CARACS_Y_XP = CARACS_Y_FOND + 84;
    public static final int CARACS_X_FAME = CARACS_X_FOND + 16;
    public static final int CARACS_Y_FAME = CARACS_Y_FOND + 123;
    public static final int CARACS_X_HP = CARACS_X_FOND + 16;
    public static final int CARACS_Y_HP = CARACS_Y_FOND + 162;
    public static final int CARACS_X_MP = CARACS_X_FOND + 17;
    public static final int CARACS_Y_MP = CARACS_Y_FOND + 182;
    public static final int CARACS_X_ATK = CARACS_X_FOND + 16;
    public static final int CARACS_Y_ATK = CARACS_Y_FOND + 202;
    public static final int CARACS_X_DEF = CARACS_X_FOND + 16;
    public static final int CARACS_Y_DEF = CARACS_Y_FOND + 222;
    public static final int CARACS_X_SPD = CARACS_X_FOND + 16;
    public static final int CARACS_Y_SPD = CARACS_Y_FOND + 242;
    public static final int CARACS_X_DEX = CARACS_X_FOND + 16;
    public static final int CARACS_Y_DEX = CARACS_Y_FOND + 262;
    public static final int CARACS_X_VIT = CARACS_X_FOND + 16;
    public static final int CARACS_Y_VIT = CARACS_Y_FOND + 282;
    public static final int CARACS_X_WIS = CARACS_X_FOND + 15;
    public static final int CARACS_Y_WIS = CARACS_Y_FOND + 302;
    public static final int CARACS_X_MAX = CARACS_X_FOND + 305;
    
    public static final int CONFIRMJETER_X_FOND = 225;
    public static final int CONFIRMJETER_Y_FOND = 187;
    public static final int CONFIRMJETER_Y_TEXT = CONFIRMJETER_Y_FOND + 30;
    public static final int CONFIRMJETER_Y_NOMOBJET = CONFIRMJETER_Y_TEXT + 20;
    public static final int CONFIRMJETER_X_OUI = CONFIRMJETER_X_FOND + 57;
    public static final int CONFIRMJETER_Y_OUI = CONFIRMJETER_Y_NOMOBJET + 50;
    public static final int CONFIRMJETER_X_NON = CONFIRMJETER_X_FOND + 229;
    public static final int CONFIRMJETER_Y_NON = CONFIRMJETER_Y_NOMOBJET + 50;
    
    public static final int INFOBULLE_X_FOND = 0;
    public static final int INFOBULLE_Y_FOND = 314;
    public static final int INFOBULLE_Y_NOMBOJET = INFOBULLE_Y_FOND + 15;
    public static final int INFOBULLE_X_NIVEAU = INFOBULLE_X_FOND + 4;
    public static final int INFOBULLE_Y_NIVEAU = INFOBULLE_Y_FOND + 4;
    public static final int INFOBULLE_Y_DESC = INFOBULLE_Y_FOND + 50;
    public static final int INFOBULLE_ESP_LIGNES = 20;
    public static final int INFOBULLE_X_DESC = INFOBULLE_X_FOND + 10;
    public static final int INFOBULLE_2X_DESC = 140;
    
    public static final int CARTE_X_POPMOB = 387;
    public static final int CARTE_Y_POPMOB = 287;
    public static final int CARTE_X_RAMASSER = 200;
    public static final int CARTE_Y_RAMASSER = MENUBARRE_Y_BARRE - 20;
    public static final int CARTE_X_CADRELOOT = 200;
    public static final int CARTE_Y_CADRELOOT = CARTE_Y_RAMASSER - 94;
    public static final int CARTE_X_LOOTOBJ = CARTE_X_CADRELOOT + 9;
    public static final int CARTE_Y_LOOTOBJ = CARTE_Y_CADRELOOT + 9;
    public static final int CARTE_ESP_LOOTOBJ = 42;
}